### ISSUE TITLE
Type Support in Svelte Files?

### ISSUE THREAD

**Issue by Mat4m0** [progressify/django-inertia-svelte-template-starter#1]
Hi, 
first, many thanks for creating just a wonderful template!

I just have a question regarding type support in the Svelte Files. 
Would this be possible at all? 

Greetings 
Mat

**Comment by progressify** [comment]
Hi, you mean using Typescript in Svelte?

**Comment by progressify** [comment]
Close.
If you still need support, pls open again this issue.
